// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// APIResponseSignUp Api response sign up
//
// swagger:model ApiResponseSignUp
type APIResponseSignUp struct {

	// code
	Code int32 `json:"code,omitempty"`

	// token
	Token string `json:"token,omitempty"`
}

// Validate validates this Api response sign up
func (m *APIResponseSignUp) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this Api response sign up based on context it is used
func (m *APIResponseSignUp) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *APIResponseSignUp) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APIResponseSignUp) UnmarshalBinary(b []byte) error {
	var res APIResponseSignUp
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
