// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// OrderItemResponse order item response
//
// swagger:model OrderItemResponse
type OrderItemResponse struct {

	// orderid
	Orderid string `json:"orderid,omitempty"`

	// productid
	Productid string `json:"productid,omitempty"`

	// quantity
	Quantity uint64 `json:"quantity,omitempty"`

	// userid
	Userid string `json:"userid,omitempty"`
}

// Validate validates this order item response
func (m *OrderItemResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this order item response based on context it is used
func (m *OrderItemResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *OrderItemResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OrderItemResponse) UnmarshalBinary(b []byte) error {
	var res OrderItemResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
