// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// OrderAPI order API
//
// swagger:model OrderAPI
type OrderAPI struct {

	// iscanceled
	Iscanceled bool `json:"iscanceled,omitempty"`

	// orderdate
	// Format: date-time
	Orderdate strfmt.DateTime `json:"orderdate,omitempty"`

	// orderitems
	Orderitems []*OrderItemResponse `json:"orderitems"`

	// orderprice
	Orderprice int64 `json:"orderprice,omitempty"`

	// userid
	Userid string `json:"userid,omitempty"`
}

// Validate validates this order API
func (m *OrderAPI) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateOrderdate(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateOrderitems(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *OrderAPI) validateOrderdate(formats strfmt.Registry) error {
	if swag.IsZero(m.Orderdate) { // not required
		return nil
	}

	if err := validate.FormatOf("orderdate", "body", "date-time", m.Orderdate.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *OrderAPI) validateOrderitems(formats strfmt.Registry) error {
	if swag.IsZero(m.Orderitems) { // not required
		return nil
	}

	for i := 0; i < len(m.Orderitems); i++ {
		if swag.IsZero(m.Orderitems[i]) { // not required
			continue
		}

		if m.Orderitems[i] != nil {
			if err := m.Orderitems[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("orderitems" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("orderitems" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this order API based on the context it is used
func (m *OrderAPI) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateOrderitems(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *OrderAPI) contextValidateOrderitems(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Orderitems); i++ {

		if m.Orderitems[i] != nil {
			if err := m.Orderitems[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("orderitems" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("orderitems" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *OrderAPI) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OrderAPI) UnmarshalBinary(b []byte) error {
	var res OrderAPI
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
